version: "3"

services:
  database: 
    image: postgres
    container_name: database_space
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=space
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=space
    volumes:
      - pgdata:/data/postgres

  
 # redis:
 #   image: redis:alpine
 #   ports: 
 #     - 6379:6379



  #app:
  #  build: .
  #  container_name: space
  #  restart: always
  #  ports: 
  #    - 3333:3333
  #    - 9229:9229
  #  volumes: 
  #    - .:/usr/app
  #  links: 
  #    - database
  #  depends_on:
  #    - database



volumes:
  pgdata:
    driver: local